#[path = "beatmap/profile_repo.rs"]
pub mod beatmap_profile_repo;
#[path = "beatmapset/profile_repo.rs"]
pub mod beatmapset_profile_repo;
#[path = "beatmapset/cache_repo.rs"]
pub mod beatmapset_repo;
#[path = "beatmapset/snapshot_weekly_repo.rs"]
pub mod beatmapset_snapshot_weekly_repo;
#[path = "leaderboard/position_current_repo.rs"]
pub mod leaderboard_position_current_repo;
#[path = "mapper/aggregate_snapshot_weekly_repo.rs"]
pub mod mapper_aggregate_snapshot_weekly_repo;
#[path = "mapper/profile_repo.rs"]
pub mod mapper_profile_repo;
#[path = "mapper/stats_current_repo.rs"]
pub mod mapper_stats_current_repo;
#[path = "osu/user_beatmapset_repo.rs"]
pub mod osu_user_beatmapset_repo;
#[path = "osu/user_repo.rs"]
pub mod osu_user_repo;
#[path = "mapper/ua_repo.rs"]
pub mod ua_mapper_repo;
