services:
  postgres:
    image: postgres:17.7-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  worker:
    profiles:
      - worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  postgres_data:
