use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(MapperProfiles::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(MapperProfiles::OsuUserId)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(MapperProfiles::Username).string().not_null())
                    .col(
                        ColumnDef::new(MapperProfiles::AvatarUrl)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(MapperProfiles::Country).string().not_null())
                    .col(
                        ColumnDef::new(MapperProfiles::CountryCode)
                            .char_len(2)
                            .not_null(),
                    )
                    .col(ColumnDef::new(MapperProfiles::CoverUrl).string().not_null())
                    .col(
                        ColumnDef::new(MapperProfiles::PrimaryMode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::JoinDate)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(ColumnDef::new(MapperProfiles::LastVisit).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(MapperProfiles::MappingFollowers)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::KudosuAvailable)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::KudosuTotal)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::BadgesJson)
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'[]'::jsonb")),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::GroupsJson)
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'[]'::jsonb")),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::IsBng)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::IsNat)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::IsGmt)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::IsLimitedBn)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::IsFullBn)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::CachedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(MapperProfiles::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_mapper_profiles_country_code")
                    .table(MapperProfiles::Table)
                    .if_not_exists()
                    .col(MapperProfiles::CountryCode)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_mapper_profiles_updated_at")
                    .table(MapperProfiles::Table)
                    .if_not_exists()
                    .col(MapperProfiles::UpdatedAt)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(MapperProfiles::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum MapperProfiles {
    Table,
    OsuUserId,
    Username,
    AvatarUrl,
    Country,
    CountryCode,
    CoverUrl,
    PrimaryMode,
    JoinDate,
    LastVisit,
    MappingFollowers,
    KudosuAvailable,
    KudosuTotal,
    BadgesJson,
    GroupsJson,
    IsBng,
    IsNat,
    IsGmt,
    IsLimitedBn,
    IsFullBn,
    CachedAt,
    CreatedAt,
    UpdatedAt,
}
