use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(BeatmapsetSnapshotsWeekly::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::OsuBeatmapsetId)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::SnapshotWeek)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::Status)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::Playcount)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::FavouriteCount)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::Rating)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::AvgPasscount)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::AvgPassRate)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::MinPassRate)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::MaxPassRate)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::LastUpdated)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetSnapshotsWeekly::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .primary_key(
                        Index::create()
                            .col(BeatmapsetSnapshotsWeekly::OsuBeatmapsetId)
                            .col(BeatmapsetSnapshotsWeekly::SnapshotWeek),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_beatmapset_snapshots_weekly_lookup")
                    .table(BeatmapsetSnapshotsWeekly::Table)
                    .if_not_exists()
                    .col(BeatmapsetSnapshotsWeekly::SnapshotWeek)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(BeatmapsetSnapshotsWeekly::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum BeatmapsetSnapshotsWeekly {
    Table,
    OsuBeatmapsetId,
    SnapshotWeek,
    Status,
    Playcount,
    FavouriteCount,
    Rating,
    AvgPasscount,
    AvgPassRate,
    MinPassRate,
    MaxPassRate,
    LastUpdated,
    UpdatedAt,
}
