use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(MapperStatsCurrent::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(MapperStatsCurrent::OsuUserId)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::TotalMapsets)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::RankedMapsets)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::LovedMapsets)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::GuestMapsets)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::NominatedMapsets)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::GraveyardMapsets)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::PendingMapsets)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::TotalPlaycount)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::AvgRating)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::WeightedRating)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::AvgStars)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::MinStars)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::MaxStars)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::AvgBpm)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::AvgLengthSeconds)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::AvgAr)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::AvgCs)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::AvgOd)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::AvgHp)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::FirstSubmittedDate)
                            .timestamp_with_time_zone(),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::FirstRankedDate)
                            .timestamp_with_time_zone(),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::LastMapsetUpdatedAt)
                            .timestamp_with_time_zone(),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::MainMode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::MappingFollowers)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::KudosuTotal)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::HasRanked)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::HasLoved)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::HasGuest)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::HasNominated)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(MapperStatsCurrent::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_mapper_stats_current_ranked")
                    .table(MapperStatsCurrent::Table)
                    .if_not_exists()
                    .col(MapperStatsCurrent::RankedMapsets)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_mapper_stats_current_playcount")
                    .table(MapperStatsCurrent::Table)
                    .if_not_exists()
                    .col(MapperStatsCurrent::TotalPlaycount)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(MapperStatsCurrent::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum MapperStatsCurrent {
    Table,
    OsuUserId,
    TotalMapsets,
    RankedMapsets,
    LovedMapsets,
    GuestMapsets,
    NominatedMapsets,
    GraveyardMapsets,
    PendingMapsets,
    TotalPlaycount,
    AvgRating,
    WeightedRating,
    AvgStars,
    MinStars,
    MaxStars,
    AvgBpm,
    AvgLengthSeconds,
    AvgAr,
    AvgCs,
    AvgOd,
    AvgHp,
    FirstSubmittedDate,
    FirstRankedDate,
    LastMapsetUpdatedAt,
    MainMode,
    MappingFollowers,
    KudosuTotal,
    HasRanked,
    HasLoved,
    HasGuest,
    HasNominated,
    UpdatedAt,
}
