use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(BeatmapsetProfiles::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::OsuBeatmapsetId)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::CreatorId)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::CreatorName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::Artist)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BeatmapsetProfiles::ArtistUnicode).string())
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::Title)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BeatmapsetProfiles::TitleUnicode).string())
                    .col(ColumnDef::new(BeatmapsetProfiles::Source).text().not_null())
                    .col(ColumnDef::new(BeatmapsetProfiles::Tags).text().not_null())
                    .col(ColumnDef::new(BeatmapsetProfiles::Genre).string())
                    .col(ColumnDef::new(BeatmapsetProfiles::Language).string())
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::Status)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::SubmittedDate)
                            .timestamp_with_time_zone(),
                    )
                    .col(ColumnDef::new(BeatmapsetProfiles::RankedDate).timestamp_with_time_zone())
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::LastUpdated)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::DiscussionEnabled)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::DiscussionLocked)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::CanBeHyped)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::IsScoreable)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::DownloadDisabled)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::Nsfw)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::Video)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::Storyboard)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::Spotlight)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::Playcount)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::FavouriteCount)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::Rating)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::HypeCurrent)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::HypeRequired)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::NominationsCurrent)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::CoverUrl)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::CardUrl)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::PreviewUrl)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::Bpm)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::DifficultyCount)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::CachedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(BeatmapsetProfiles::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_beatmapset_profiles_creator_id")
                    .table(BeatmapsetProfiles::Table)
                    .if_not_exists()
                    .col(BeatmapsetProfiles::CreatorId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_beatmapset_profiles_last_updated")
                    .table(BeatmapsetProfiles::Table)
                    .if_not_exists()
                    .col(BeatmapsetProfiles::LastUpdated)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(BeatmapsetProfiles::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum BeatmapsetProfiles {
    Table,
    OsuBeatmapsetId,
    CreatorId,
    CreatorName,
    Artist,
    ArtistUnicode,
    Title,
    TitleUnicode,
    Source,
    Tags,
    Genre,
    Language,
    Status,
    SubmittedDate,
    RankedDate,
    LastUpdated,
    DiscussionEnabled,
    DiscussionLocked,
    CanBeHyped,
    IsScoreable,
    DownloadDisabled,
    Nsfw,
    Video,
    Storyboard,
    Spotlight,
    Playcount,
    FavouriteCount,
    Rating,
    HypeCurrent,
    HypeRequired,
    NominationsCurrent,
    CoverUrl,
    CardUrl,
    PreviewUrl,
    Bpm,
    DifficultyCount,
    CachedAt,
    CreatedAt,
    UpdatedAt,
}
