use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(BeatmapProfiles::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(BeatmapProfiles::OsuBeatmapId)
                            .big_integer()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::OsuBeatmapsetId)
                            .big_integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::CreatorId)
                            .big_integer()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BeatmapProfiles::Version).string().not_null())
                    .col(ColumnDef::new(BeatmapProfiles::Mode).string().not_null())
                    .col(
                        ColumnDef::new(BeatmapProfiles::Stars)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::Ar)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::Cs)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::Od)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::Hp)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::Bpm)
                            .float()
                            .not_null()
                            .default(0.0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::SecondsTotal)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::SecondsDrain)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(BeatmapProfiles::MaxCombo).integer())
                    .col(
                        ColumnDef::new(BeatmapProfiles::Playcount)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::Passcount)
                            .big_integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::CountCircles)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::CountSliders)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::CountSpinners)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::OwnersJson)
                            .json_binary()
                            .not_null()
                            .default(Expr::cust("'[]'::jsonb")),
                    )
                    .col(ColumnDef::new(BeatmapProfiles::Status).string().not_null())
                    .col(
                        ColumnDef::new(BeatmapProfiles::IsScoreable)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::LastUpdated)
                            .timestamp_with_time_zone()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::CachedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::CreatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(BeatmapProfiles::UpdatedAt)
                            .timestamp_with_time_zone()
                            .not_null()
                            .default(Expr::current_timestamp()),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_beatmap_profiles_mapset_id")
                    .table(BeatmapProfiles::Table)
                    .if_not_exists()
                    .col(BeatmapProfiles::OsuBeatmapsetId)
                    .to_owned(),
            )
            .await?;

        manager
            .create_index(
                Index::create()
                    .name("idx_beatmap_profiles_mode")
                    .table(BeatmapProfiles::Table)
                    .if_not_exists()
                    .col(BeatmapProfiles::Mode)
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(BeatmapProfiles::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await
    }
}

#[derive(DeriveIden)]
enum BeatmapProfiles {
    Table,
    OsuBeatmapId,
    OsuBeatmapsetId,
    CreatorId,
    Version,
    Mode,
    Stars,
    Ar,
    Cs,
    Od,
    Hp,
    Bpm,
    SecondsTotal,
    SecondsDrain,
    MaxCombo,
    Playcount,
    Passcount,
    CountCircles,
    CountSliders,
    CountSpinners,
    OwnersJson,
    Status,
    IsScoreable,
    LastUpdated,
    CachedAt,
    CreatedAt,
    UpdatedAt,
}
