#[path = "beatmap/profile.rs"]
pub mod beatmap_profile;
#[path = "beatmapset/extra.rs"]
pub mod beatmapset_extra;
#[path = "beatmapset/profile.rs"]
pub mod beatmapset_profile;
#[path = "beatmapset/snapshot_weekly.rs"]
pub mod beatmapset_snapshot_weekly;
#[path = "leaderboard/position_current.rs"]
pub mod leaderboard_position_current;
#[path = "mapper/aggregate_snapshot_weekly.rs"]
pub mod mapper_aggregate_snapshot_weekly;
#[path = "mapper/stats_current.rs"]
pub mod mapper_stats_current;
#[path = "osu/user.rs"]
pub mod osu_user;
#[path = "osu/user_beatmapset.rs"]
pub mod osu_user_beatmapset;
#[path = "system/scan_state.rs"]
pub mod scan_state;
#[path = "mapper/ua.rs"]
pub mod ua_mapper;
