name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - "**/*.md"

jobs:
  release:
    name: Release Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.93.0
      - uses: Swatinem/rust-cache@v2
      - name: cargo build --release
        run: cargo build --workspace --release

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.93.0
      - uses: Swatinem/rust-cache@v2
      - name: cargo test
        run: cargo test --workspace --all-features --all-targets

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.93.0
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: cargo clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

